## Intro
##### In this notebook is some stuff related too:
- Intro to tensors
- Info to tensors
- Working with tensors
- Tensor & Numpy
- using @tf.function to speedup python
- GPU (Mac uses tensorflow-metal)


In [1]:
import tensorflow as tf

print(tf.config.list_physical_devices())
gpus = tf.config.list_physical_devices('GPU')

print(gpus)


/Users/kraytor/Projects/TensorflowCourse/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


### Intro to Tensors
##### * These are all simple objects you'll be using with imported data in the future

In [18]:
import tensorflow as tf

print(tf.__version__)

def describe(x):
    print(
        "info: ", x,
        "\ndimensions: ", x.ndim,
    )

2.18.0


#### Summary
* Scalar: single number
* Vector: a number with direction
* Matrix: 2-dim 
* Tensor: n-dim

In [30]:
scalar = tf.constant(7)
vector = tf.constant([10,10])
matrix = tf.constant([[10,7],
                      [7,10],
                      [8,9]])
tensor = tf.constant([[[1.], [2.], [3.]],[ [3.], [4.], [5.]]])
# describe(tensor)

### Creating tensors with `tf.Variable()`

In [36]:
changeable_tensor = tf.Variable([10,7])

changeable_tensor[0].assign(100)


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([100,   7], dtype=int32)>

🔑Note: Rarely I will use Variable and constant as itll be decided by tf in the future when data is read in

### Random Tensors

In [60]:
seed = 42

robj = tf.random.Generator.from_seed(seed)
r1 = robj.normal(shape=(2,3))
r2 = robj.normal(shape=(2,3))
r1, r2

# Shuffle a thing
r2_randomized = tf.random.shuffle(r2, seed=42)
r2, r2_randomized





(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[ 0.17522675,  0.7110553 ,  0.54882437],
        [ 0.14896014, -0.54757947,  0.6163437 ]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[ 0.14896014, -0.54757947,  0.6163437 ],
        [ 0.17522675,  0.7110553 ,  0.54882437]], dtype=float32)>)

### Other Ways

In [61]:
print(tf.ones(shape=(2,3)))
print(tf.zeros(shape=(2,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


### Numpy Tensors

In [63]:
# A matrix or tensor is typically represented by a capital letter (e.g. X or A) where as a vector is typically represented by a lowercase letter 

import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25
A = tf.constant(numpy_A,  
                shape=[2, 4, 3]) # note: the shape total (2*4*3) has to match the number of elements in the array
numpy_A, A

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32),
 <tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]], dtype=int32)>)

### Tensor variable data

In [65]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros([2, 3, 4, 5])


print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array


Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): 120


In [66]:
# Get the first 2 items of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [68]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])

# Get the last item of each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [75]:
import numpy as np

x = [np.random.randint(0,5) for _ in range(10)]
print(x)

tf.one_hot(x, depth=5)

[2, 1, 2, 0, 3, 0, 0, 2, 3, 4]


<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

zsh:1: command not found: nvidia-smi
